plugins/module_utils/vm.py
There was some sanity issue left out and this is a fix for it.
=> Sanity fix after commiting issue 7

README.md, galaxy.yml
This is what is shown on https://galaxy.ansible.com/scale_computing/hypercore, so we need clickable links.
=> Link for docs

examples/vm_info.yml, examples/vm_replication_info.yml, plugins/module_utils/snapshot_schedule.py, plugins/modules/snapshot_schedule.py, tests/integration/targets/snapshot_schedule/tasks/main.yml, tests/unit/plugins/module_utils/test_snapshot_schedule.py, tests/unit/plugins/modules/test_snapshot_schedule.py
=> Fix snapshot_schedule idempotency.

examples/list_vms_with_ide_disk.yml, plugins/module_utils/vm.py, plugins/modules/vm.py, plugins/modules/vm_disk.py, tests/integration/targets/vm/tasks/01_main.yml, tests/integration/targets/vm_boot_devices/tasks/main.yml, tests/integration/targets/vm_disk/tasks/main.yml, tests/integration/targets/vm_git_issues/tasks/issue_11_empty_ide_cdrom.yml, tests/integration/targets/vm_git_issues/tasks/issue_12_machine_types.yml, tests/integration/targets/vm_git_issues/tasks/issue_15_tiering_priority.yml, tests/integration/targets/vm_git_issues/tasks/issue_3_enlarging_disk_is_triggering_restart.yml, tests/integration/targets/vm_git_issues/tasks/issue_4_vcpu_set_to_0.yml, tests/integration/targets/vm_git_issues/tasks/issue_7_problem_with_power_state.yml, tests/integration/targets/vm_git_issues/tasks/main.yml, tests/integration/targets/vm_nic_info/tasks/main.yml, tests/integration/targets/vm_node_affinity/tasks/main.yml, tests/integration/targets/vm_params/tasks/main.yml, tests/unit/plugins/module_utils/test_replication.py, tests/unit/plugins/module_utils/test_vm.py, tests/unit/plugins/modules/test_vm.py, tests/unit/plugins/modules/test_vm_boot_devices.py, tests/unit/plugins/modules/test_vm_clone.py, tests/unit/plugins/modules/test_vm_disk.py, tests/unit/plugins/modules/test_vm_export.py, tests/unit/plugins/modules/test_vm_import.py, tests/unit/plugins/modules/test_vm_info.py, tests/unit/plugins/modules/test_vm_nic.py, tests/unit/plugins/modules/test_vm_replication.py, tests/unit/plugins/modules/test_vm_replication_info.py
Resolves #12 
Has to be merged after merging https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/36. Suggest also reviewing it after merging https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/36 since some rebasing has been done from https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/36.
=> Add support for vm machine types

plugins/module_utils/rest_client.py, plugins/modules/vm_info.py
Use only with read only endpoints.
=> Cached rest client

.github/workflows/ci-test.yml, .gitlab-ci.yml, ci-infra/gitlab-dynamic-pipeline/child-pipeline-gitlab-ci.yml.head, tests/integration/ci_replica_cleanup.yml
Add a playbook to remove VM replicas created by CI jobs on replication destination cluster
Fixes #25
=> cleanup "dangling" replicated VMs

plugins/doc_fragments/cluster_instance.py
=> Fix SC_URL vs SC_HOST in documentation

examples/virtual_disk.yml, plugins/module_utils/rest_client.py, plugins/modules/api.py, tests/unit/plugins/modules/test_api.py
=> api module: Add support for PUT methods

.github/workflows/ci-test.yml
Adding concurrency to CI file.
Only the latest workflow should be ran per branch, older are cancelled.
=> Integration test auto cancel

changelogs/fragments/73_dns_config_modules.yml, changelogs/fragments/release_111.yml, examples/dns_config.yml, examples/dns_config_info.yml, plugins/module_utils/dns_config.py, plugins/modules/dns_config.py, plugins/modules/dns_config_info.py, tests/integration/targets/dns_config/tasks/main.yml, tests/integration/targets/dns_config_info/tasks/main.yml, tests/unit/plugins/module_utils/test_dns_config.py, tests/unit/plugins/modules/test_dns_config.py, tests/unit/plugins/modules/test_dns_config_info.py
Created a module for DNSConfig: ``dns_config.py`` (in ``module_utils/`` and ``modules/``), ``dns_config_info.py`` (in ``modules/``) and integration tests for the newly created module ``dns_config_info.py`` and ``dns_config.py``
=> Added dns_config with info and integration tests

tests/integration/integration_config.yml.template
We just forgot to add variable to the `integration_config.yml.template`.
=> Add sc_timeout to integration_config.yml.template

plugins/module_utils/typed_classes.py, plugins/modules/user.py
- Removed unnecassary `dict[Any]` from `TypedDiff`.
- Small fix to an empty output in User module.
=> Removing dict[Any, Any] from TypedDiff

plugins/modules/smtp.py, tests/integration/integration_config.yml.template, tests/integration/targets/smtp/tasks/01_smtp_info.yml, tests/integration/targets/smtp/tasks/02_smtp.yml, tests/integration/targets/smtp/tasks/helper_api_smtp_create_one.yml, tests/integration/targets/smtp/tasks/helper_api_smtp_delete_all.yml, tests/integration/targets/smtp/tasks/helper_api_smtp_reset.yml, tests/integration/targets/smtp/tasks/main.yml
=> Fix Smtp bug on empty cluster

plugins/modules/smtp.py, tests/integration/targets/smtp/tasks/02_smtp.yml
=> Smtp fix from addres reset

tests/integration/targets/dns_config/tasks/02_dns_config.yml
At least the first entry should be a valid DNS resolver server.
=> Ensure we have always a valid DNS resolver configured

.github/ISSUE_TEMPLATE/Bug_report.md
=> bug report template

plugins/modules/cluster_name.py, tests/integration/targets/cluster_name/tasks/main.yml
Corrected version requirement.
Also integration test updated so it doesn't fail in case if hcversion doesn't support cluster name patch method.
=> Cluster_name update version check

.github/workflows/ci-test.yml, plugins/module_utils/cluster.py, plugins/modules/cluster_shutdown.py, tests/integration/integration_config.yml.template, tests/integration/targets/cluster_shutdown/tasks/main.yml, tests/unit/plugins/module_utils/test_cluster.py
=> Add cluster_shutdown module

plugins/modules/registration.py, tests/integration/targets/registration/tasks/main.yml, tests/unit/plugins/modules/test_registration.py
Also check what fields are returned by registration module
=> Remove bogus vm_rebooted in registration module output

.github/workflows/integ-test.yml, plugins/module_utils/hypercore_version.py, plugins/module_utils/typed_classes.py, plugins/modules/version_update.py, plugins/modules/version_update_info.py, plugins/modules/version_update_status_info.py, tests/integration/integration_config.yml.template, tests/integration/targets/version_update/tasks/main.yml, tests/integration/targets/version_update_info/tasks/main.yml, tests/integration/targets/version_update_status_info/tasks/main.yml, tests/unit/plugins/module_utils/test_hypercore_version.py, tests/unit/plugins/modules/test_cluster_info.py, tests/unit/plugins/modules/test_version_update.py, tests/unit/plugins/modules/test_version_update_info.py, tests/unit/plugins/modules/test_version_update_status_info.py
Added modules:
- version_update_info (returns list of available updates)
- version_update (applies selected updated to the cluster)
- version_update_status_info (returns status of the latest applied update)
=> Version management

plugins/module_utils/hypercore_version.py, plugins/modules/cluster_name.py, plugins/modules/virtual_disk_info.py
Make it a one function call.
This might have to be implemented in multiple modules in the future.
Easier to maintain and fix if necessary ... all in one place.
=> Hypercore version

examples/virtual_disk_info.yml
Because examples are nice to have. And I just needed to list all virtual_disks :)
=> Add example for virtual_disk_info module

roles/cluster_config/meta/argument_specs.yml, roles/version_update_single_node/meta/argument_specs.yml, roles/version_update_single_node/tasks/shutdown_vms.yml, roles/version_update_single_node/tasks/wait_vm_shutdown.yml
=> fix formatting

.github/workflows/ci-test.yml
HTML will be there for manual review.
Sample CI run - https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4502749847.
I need to unzip whole zip file to get valid links.
=> Store rendered html as github artifact

examples/virtual_disk.yml
Use virtual_disk module instead of api module
=> Update virtual disk example to use virtual_disk module

.github/workflows/integ-test.yml
Seems a valid LANG is needed with ansible 2.15
=> CI use LANG=C.UTF-8 for integration tests

.github/workflows/ci-test.yml, .github/workflows/integ-test.yml, .github/workflows/static.yml, ci-infra/docker-image/Dockerfile, ci-infra/docker-image/build.sh
- [ci: add locales to docker image](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/255/commits/6d4b29c47b6a17e3b75ca561ca7cd63930c9b779)
- [ci: bump docker image version to 8](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/255/commits/af0716d5258a981a77c312e2344bb46236debd0c)
- [ci: use docker image version 8](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/255/commits/ac6882489f950774a024a3abb2fc05b6b6f5ea61)
=> ci: update docker image and workflows

.github/workflows/integ-test.yml, tests/integration/integration_config.yml.j2
=> ci: add 9.3.x VSNS to integration test matrix

Makefile, docs/rst/extra/password_masking.rst, docs/rst/index.rst
Document how Ansible mask password value.
=> Document password masking

plugins/modules/vm_snapshot.py
=> Describe why vm_snapshot does not create snapshots with duplicated label

.github/workflows/ansible-test.yml, .github/workflows/ci-test.yml, .github/workflows/files/ansible-test-units-matrix.yml, .github/workflows/integ-test.yml, .github/workflows/static.yml, ci-infra/docker-image/Dockerfile, ci-infra/docker-image/README.md, ci-infra/docker-image/build.sh, meta/runtime.yml, plugins/inventory/hypercore.py, plugins/module_utils/client.py, plugins/module_utils/hypercore_version.py, plugins/module_utils/task_tag.py, plugins/modules/vm_export.py, plugins/modules/vm_nic.py, plugins/modules/vm_replication_info.py, test.requirements, tests/unit/plugins/module_utils/test_check_local_time.py
Add ansible-core 2.16 to test matrix. Also new CI image was build and pushed to quay.io
Small style changes were needed for ansible sanity test to pass.
=> Ci ansible core 2.16

.github/workflows/integ-test.yml, tests/integration/integration_config.yml.j2
=> ci: replace HyperCore 9.3.1 with 9.3.5

.github/workflows/static.yml
The docs failed to build during the last release. This fixes the docs workflow.
=> Fix docs workflow

DEVELOPMENT.md
Just trying to list what needs to be done for VSNS. Maybe a better place for this is issue template, with a check list like we have for release. Would person that creates VSNS (who is this - Sam, Dave, Alex maybe) prefer an issue template?
Likely more steps are needed, but I'm not aware how CI VSNS nodes are created.
=> List steps needed to add new CI cluster

.github/workflows/integ-test.yml, examples/url2template/template2vm.yml, roles/template2vm/defaults/main.yml, roles/template2vm/meta/argument_specs.yml, roles/template2vm/tasks/main.yml, tests/integration/targets/iso/tasks/main.yml, tests/integration/targets/role_template2vm/01_minimal.yml, tests/integration/targets/role_template2vm/02_booted.yml, tests/integration/targets/role_template2vm/02_vars.yml, tests/integration/targets/role_template2vm/03_extra_nics.yml, tests/integration/targets/role_template2vm/cleanup.yml, tests/integration/targets/role_template2vm/hypercore_inventory.yml, tests/integration/targets/role_template2vm/prepare.yml, tests/integration/targets/role_template2vm/runme.sh, tests/integration/targets/role_template2vm/templates/meta-data.ubuntu-20.04.yml.j2, tests/integration/targets/role_template2vm/templates/user-data.ubuntu-20.04.yml.j2, tests/integration/targets/role_template2vm/vars.yml, tests/integration/targets/role_url2template/tasks/main.yml
Support extra NICs with VLAN in role template2vm.
Also fix missing default values for optional params.
Add integration tests.
Also remove jinja2 templating from an assert in iso test.
=> Support extra NICs with VLAN in role template2vm

README.md, meta/runtime.yml, roles/check_local_time/meta/main.yml, roles/cluster_config/meta/main.yml, roles/template2vm/meta/main.yml, roles/url2template/meta/main.yml, roles/version_update_single_node/meta/main.yml
The changes were requested in "Ansible Partner Announcements - May 2024"
=> Update readme, bump min_ansible_version

.github/workflows/integ-test.yml, CHANGELOG.rst, README.md, changelogs/changelog.yaml, galaxy.yml
=> Release 1.5.0

plugins/modules/oidc_config.py
This should reduce likelihood of failing oidc_config test due to 50x error. I was not able to reproduce 50x error for `updated_oidc = Oidc.get(rest_client)` during local testing. But this was main suspect for failing test https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/10554972693/job/29264590244#step:7:105
=> oidc_config, retry also '"safe" GET

plugins/modules/vm.py, plugins/modules/vm_params.py
=> Update docs about VM being rebooted if needed

.github/workflows/release.yml
=> ci: use ansible/ansible-content-actions for publish job
