tests/integration/targets/vm_replication/tasks/main.yml
The second one was not really used, no need for it to be confiugred on test cluster.
=> CI vm_replication integration test uses a single remote cluster

plugins/module_utils/vm.py, tests/unit/plugins/module_utils/test_vm.py
The VM uuid is already in PATCH URL path, it is not needed in PATCH data/payload.
v9.1 did not complain, v9.2 does complain.
Fix by @ddemlow
=> Fix changing boot devices order for HyperCore v9.2

plugins/inventory/hypercore.py, tests/integration/targets/inventory/prepare.yml
The HyperCore web UI does not allow tag with '=', so we must not use it.
=> Replace '=' with '__' (double underscore) in tags recognized by inventory plugin

.ansible-lint
The "on:" keyword contains a list of triggers, but ansible-lint thinks it is boolean and want it to be true/false.
=> ansible-lint should not check github workflows

plugins/modules/vm_replication_info.py, tests/integration/targets/vm_replication_info/tasks/main.yml
How the module should behave:
- if VM is not present, is should fail - CI test added for this case
- if VM is present, and replication is not configured, the module should:
- succeed
- `records` should be an empty list
This way, `records` list does not contain element with `vm_name` equal to VM module is reporting replication info about.
This is consistent with behavior when module is called with ommited `vm_name` param - unreplicated VMs are just not included into the returned `records`. 
Fixes #24
=> Fix vm_replication_info for unreplicated vm

examples/README.md, examples/vm_info.yml, examples/vm_replication_info.yml
Nothing special in those two playbooks, they are just ready-to-run example playbooks.
@ddemlow Are such examples something that you would find useful when you craft your own playbooks? The `examples/` were added with intention that endusers could run then immediately (ok, after installing ansible and `export SC_HOST=...`.
=> Add example playbooks for vm_info and vm_replication_info modules

examples/list_vms_with_ide_disk.yml
Inline python is used to filter the all VMs result and return only VM names  that have at least one IDE disk.
Hope this helps :)
=> List all VMs that have at least one IDE disk

plugins/module_utils/vm.py
For some instances API returns VirDomain with empty machineType. Ansible should work with instances like that - at least read part should not have any problems.
=> Bugfix: we do not crash if machineType is empty

plugins/module_utils/rest_client.py, tests/unit/plugins/module_utils/test_rest_client_CachedRestClient.py
If CachedRestClient was first called with non-emtpy query, then filtered data was stored into cache.
If next call would have different filter, it would get a wrong response.
Also added some tests for this class.
=> Fix CachedRestClient - filterd data was cached as if it is unfiltered

plugins/module_utils/disk.py, plugins/module_utils/vm.py, plugins/modules/vm_disk.py, tests/integration/targets/vm/tasks/01_main.yml, tests/integration/targets/vm_git_issues/tasks/issue_41_cloud_init_disks.yml, tests/integration/targets/vm_git_issues/tasks/main.yml, tests/unit/plugins/module_utils/test_vm.py
Allows for cloud init to create IDE_CDROM without deleting it as long as cloud-init ISO is still attached.
Removes cloud init CDROM when ISO is detached.
=> 41 cloud init disk logic fix

tests/integration/targets/vm_clone/tasks/main.yml
changed memory configuration to 511705088 bytes which == 488MiB which displays as integer in HyperCore UI which displays in MiB.  previous setting resulted in decimal representation which could lead to compatibility issues
=> Update main.yml with memory setting for improved UI display and compatibility

tests/integration/targets/vm_clone/tasks/main.yml
made mem == 511705088 change to name: Create XLAB-vm_clone-CI_test-running  (which was the one not starting on 9.2.8 hypercore)
=> Update main.yml - set mem on name: Create XLAB-vm_clone-CI_test-running

changelogs/fragments/user_info_module.yml, plugins/module_utils/role.py, plugins/module_utils/user.py, plugins/modules/user_info.py, tests/integration/targets/user_info/tasks/main.yml, tests/unit/plugins/module_utils/test_role.py, tests/unit/plugins/module_utils/test_user.py, tests/unit/plugins/modules/test_user_info.py
=> Us01 user info module

tests/integration/cleanup/smb_cleanup.sh
I'm trying to use ansible-community/ansible-test-gh-action@release/v1 action instead of manually craft `ansible-test ...` command.
One thing it complained about was smb_cleanup.sh, it failed shellcheck test. I modify script a bit (I'm not good at bash arrays, and had problem understanding how script works), and then fixed remaining complains about escaping and quoting.
I tested a script on samba server. Two old files (`cp -a /usr/share/zoneinfo/{Cuba,Libya} /srv/integration-test-vm-export/`) were added, those needs to be deleted. One new file was created, this one needs to stay (`touch /srv/integration-test-vm-export/zaklad`). Output is
```
tests/integration/cleanup/smb_cleanup.sh 10.5.11.179 /users "fakedomain;example1" badpass; echo ret=$?
Folder: integration-test-vm-export
list_dir=  . …
```
=> Refactor smb_cleanup.sh

.github/workflows/ci-test.yml
Integration tests are run after unit tests pass.
Sanity and unit tests do not need HyperCore server, run them on public runners.
=> Delay integration tests

changelogs/fragments/support_tunnel_modules.yml, plugins/module_utils/support_tunnel.py, plugins/module_utils/typed_classes.py, plugins/modules/support_tunnel.py, plugins/modules/support_tunnel_info.py, tests/integration/targets/support_tunnel/tasks/main.yml, tests/integration/targets/support_tunnel_info/tasks/main.yml, tests/unit/plugins/module_utils/test_support_tunnel.py, tests/unit/plugins/modules/test_support_tunnel.py
Added support_tunnel and support_tunnel_info module.
=> Us03 remote support tunnels

changelogs/fragments/user_modules_type_annotation.yml, plugins/module_utils/role.py, plugins/module_utils/typed_classes.py, plugins/module_utils/user.py, plugins/modules/user.py, plugins/modules/user_info.py, pyproject.toml, tests/integration/targets/support_tunnel/tasks/main.yml
Type annotation added to user and user_info module
=> US01 - add type annotation

changelogs/fragments/email_alert.yml, examples/email_alert.yml, examples/email_alert_info.yml, plugins/module_utils/email_alert.py, plugins/module_utils/typed_classes.py, plugins/modules/email_alert.py, plugins/modules/email_alert_info.py, pyproject.toml, tests/integration/targets/email_alert/tasks/main.yml, tests/integration/targets/email_alert_info/tasks/main.yml, tests/unit/plugins/module_utils/test_email_alert.py, tests/unit/plugins/modules/test_email_alert.py, tests/unit/plugins/modules/test_email_alert_info.py
Added email alert modules (email_alert, email_alert_info)
Examples usages:
```yaml
- name: Create a new Email Alert Recipient
scale_computing.hypercore.email_alert:
email: example@example.com
state: present
- name: Update previously create Email Alert Recipient
scale_computing.hypercore.email_alert:
email: example@example.com
email_new: new@example.com
state: present
- name: Remove previously updated Email Alert Recipient
scale_computing.hypercore.email_alert:
email: new@example.com
state: absent
- name: Send test email to an Email Alert Recipient
scale_computing.hypercore.email_alert:
email: recipient@example.com
state: test
- name: Retrieve al recipients
scale_computing.hypercore.email_alert_info:
register: info
- ansible.builtin.debug:
msg: "{{ info.records }}"
```
=> Add Us11 email alert modules (email_alert, email_alert_info)

plugins/inventory/hypercore.py, plugins/module_utils/client.py, plugins/modules/dns_config.py, plugins/modules/dns_config_info.py, plugins/modules/email_alert.py, plugins/modules/email_alert_info.py, plugins/modules/smtp.py, plugins/modules/smtp_info.py, plugins/modules/time_server.py, plugins/modules/time_server_info.py, plugins/modules/time_zone.py, plugins/modules/time_zone_info.py, tests/unit/plugins/module_utils/test_client.py, tests/unit/plugins/module_utils/test_rest_client_CachedRestClient.py
But default value None for timeout is the root problem. To easy to miss you need to set timeout.
Removed all default parameter values for Client.Client(). Normal modules should use Client.get_client() anyway, and now no-one will want to use Client.Client()
=> Fix missing timeout when Client is created

.github/workflows/ansible-test.yml, .github/workflows/release.yml, DEVELOPMENT.md, galaxy.yml
Add the release.yml workflow file for automatic releases. Releases are triggered by tagging a commit with a name matching `v*.*.*`.
The workflow follows these steps:
- Verify the release by comparing the tag name with the galaxy.yml version.
- Build the collection tar file to include as a release artifact.
- Generate release notes from CHANGELOG.rst
- Create a [github release](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/releases) using the tag name
- Publish the release to ansible galaxy (**this step will fail until a valid api key is added to the repo secrets**)
=> Add release workflow

.github/workflows/ci-test.yml, changelogs/fragments/virtual_disk_info_module.yml, plugins/module_utils/hypercore_version.py, plugins/module_utils/typed_classes.py, plugins/module_utils/virtual_disk.py, plugins/modules/virtual_disk_info.py, tests/integration/targets/virtual_disk_info/tasks/main.yml, tests/unit/plugins/module_utils/test_hypercore_version.py, tests/unit/plugins/module_utils/test_virtual_disk.py, tests/unit/plugins/modules/test_virtual_disk_info.py
Module sample output is:
```
sample:
name: demo-virtual-disk
block_size: 1048576
size: 1073741824
replication_factor: 2
uuid: 7983b298-c37a-4c99-8dfe-b2952e81b092
```
`size` gets value from `capacityBytes` in API response. API field `totalAllocationBytes` is ignored, until it gets clear why it is equal to `capacityBytes`.
=> Add virtual_disk_info module

plugins/module_utils/time_zone.py, plugins/modules/time_zone.py, tests/integration/targets/time_zone/tasks/02_time_zone.yml, tests/integration/targets/time_zone/tasks/helper_api_time_zone_create_one.yml, tests/integration/targets/time_zone/tasks/helper_api_time_zone_delete_all.yml, tests/integration/targets/time_zone/tasks/helper_api_time_zone_reset.yml, tests/integration/targets/time_zone/tasks/main.yml
Fixed time_zone module not working on an empty cluster in which case it now creates one instead of printing out a warning message.
=> Time zone on empty cluster

plugins/module_utils/time_server.py, plugins/modules/time_server.py, tests/integration/targets/time_server/tasks/02_time_server.yml, tests/integration/targets/time_server/tasks/helper_api_time_server_create_one.yml, tests/integration/targets/time_server/tasks/helper_api_time_server_delete_all.yml, tests/integration/targets/time_server/tasks/helper_api_time_server_reset.yml, tests/integration/targets/time_server/tasks/main.yml
Fixed time_server module not working on an empty cluster in which case it now creates one instead of printing out a warning message.
=> Time server on empty cluster

plugins/module_utils/errors.py, plugins/modules/oidc_config.py, tests/integration/targets/oidc_config/tasks/oidc_config.yml, tests/integration/targets/oidc_config/tasks/oidc_reset.yml, tests/unit/plugins/modules/test_oidc_config.py
Module will be easier to use if ignore or retry on 500/502 error is hidden inside module.
A small stress test is added to ensure we hit the API errors frequently.
=> fix 502 bad gateway problem with oidc_config module

plugins/modules/email_alert.py, tests/unit/plugins/modules/test_email_alert.py
Unit tests for ``modules/email_alert.py`` weren't complete,
so a completion was made in ``tests/unit/plugins/modules/test_email_alert.py``.
=> Update unit tests for modules/email_alert.py

plugins/modules/syslog_server.py, tests/unit/plugins/module_utils/test_syslog_server.py, tests/unit/plugins/modules/test_syslog_server.py, tests/unit/plugins/modules/test_syslog_server_info.py
Unit tests for ``syslog_server`` module weren't yet implemented, so the implementation was added.
Tests are:
- ``tests/unit/plugins/module_utils/test_syslog_server.py``
- ``tests/unit/plugins/modules/test_syslog_server.py``
- ``tests/unit/plugins/modules/test_syslog_server_info.py``
=> Add unit tests for syslog_server module.

examples/smtp.yml, plugins/modules/smtp.py, tests/integration/integration_config.yml.template, tests/integration/targets/smtp/tasks/02_smtp.yml, tests/integration/targets/smtp/tasks/helper_api_smtp_create_one.yml, tests/unit/plugins/modules/test_smtp.py
For the ``smtp`` module is better that the ``use_auth`` param is ``read-only``, so that was updated.
=> Make use_auth read-only (remove from create/update payload).

changelogs/fragments/cluster_modules.yml, plugins/module_utils/cluster.py, plugins/modules/cluster_shutdown.py, tests/unit/plugins/module_utils/test_cluster.py
Fixed timeout error in case when a lot of VMs need to be shutdown - the timeout error is ignored (but not the UnexpectedAPIResponse error). Also get request to rest/v1/Cluster is added to check when connection is refused, and only then the cluster_shutdown module successfully exits.
=> Fix timeout error in case when a lot of VMs need to be shutdown

.github/workflows/integ-test.yml
During OIDC reconfiguration API seems to be restarted, and any other test will fail.
See https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4239901225/jobs/7368389276
- most failed jobs have 502 error.
We want to have exclude-tests list used both on scheduled run and on interactive run. On interactive run,
github.event.inputs.integ_tests_exclude is non-empty and is used. On scheduled run github.event.inputs.integ_tests_exclude is empty, so the same string is retrived from INTEG_TESTS_EXCLUDE_SCHEDULE environ variable.
=> Do not run oidc_config test with other tests

tests/integration/targets/time_server/tasks/01_time_server_info.yml, tests/integration/targets/time_zone/tasks/01_time_zone_info.yml
Ensure time_zone_info is tested with 0 and 1 time zone configured
Test https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4259825907/jobs/7412400599
failed because no timezone was present, and "actual.record.0.timeZone"
tried to get first record from empty list.
Ensure time_server_info is tested with 0 and 1 time server configured
Test
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4259825907/jobs/7412400755
failed because no timeserver was present, and "time_server.record.0.host"
tried to get first record from empty list.
=> Fix time zone and time server integ tests

.github/workflows/integ-test.yml
Job
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4259825907/jobs/7412403066 failed with
TASK [email_alert : Send test email to an existing Email Alert Recipient] ****** fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unexpected response - 400 b'{\"error\":\"SMTP unconfigured\"}'"}
The smtp test was run in parallel.
Avoid this by not running both at the same time - exclude smtp.
=> Do not run email_alert and smtp tests in parallel

plugins/module_utils/vm.py, plugins/modules/vm.py, plugins/modules/vm_params.py, tests/integration/targets/vm/tasks/03_rename.yml, tests/integration/targets/vm__rename/tasks/03_rename.yml, tests/integration/targets/vm__rename/tasks/main.yml, tests/unit/plugins/module_utils/test_vm.py, tests/unit/plugins/modules/test_vm.py
Integration test is added to show that renaming VM a second time (idempotence test) does fail in current main.
Problem is (in most places) we search for VM by `vm_name` only, but we should by `vm_name` xor `vm_name_new`.
A helper function `VM.get_by_old_or_new_name` does this, and is used in VM module.
PR was draft:
- (partially done) unit tests need to be updated
- done - sanity tests
- todo - run all integration tests
- vm_nic, vm_disk, vm_params modules should also be updated.
- I update vm_params module only, because only vm_params and vm modules have `vm_name_new` param
- maybe we can do extra cleanup, and stop using old `VM.get_by_name` - I'm not sure, need to check all affected modules.
- I didn't even try this - unit test update would be painful 
But there is enough code for first …
=> VM rename test and fix

plugins/module_utils/syslog_server.py, plugins/modules/syslog_server.py, tests/integration/targets/syslog_server/tasks/01_syslog_server_info.yml, tests/integration/targets/syslog_server/tasks/02_syslog_server.yml, tests/unit/plugins/module_utils/test_syslog_server.py, tests/unit/plugins/modules/test_syslog_server.py, tests/unit/plugins/modules/test_syslog_server_info.py
Fixed a minor issue pointed out in pull request #132.
> Info module does not convert ``SYSLOG_PROTOCOL_UDP`` to ``udp``, but it should.
> The syslog_server_info module should return values that are same as those accepted by syslog_server module.
=> Fix syslog_syslog_server_info module output, update tests.

plugins/module_utils/email_alert.py, plugins/module_utils/typed_classes.py, plugins/modules/email_alert.py, plugins/modules/email_alert_info.py, tests/integration/targets/email_alert/tasks/01_email_alert_info.yml, tests/integration/targets/email_alert/tasks/02_email_alert.yml, tests/unit/plugins/module_utils/test_email_alert.py, tests/unit/plugins/modules/test_email_alert.py, tests/unit/plugins/modules/test_email_alert_info.py
Names of return values didn't match the names of input parameters.
- renamed ``email_address`` to ``email``
=> Replace 'email_address' to 'email' in records return.

plugins/module_utils/errors.py, plugins/modules/support_tunnel.py, tests/integration/targets/support_tunnel/tasks/main.yml
In case when support tunnel code is already in use, module now raises and error.
=> Handle case when code is already in use

plugins/modules/smtp.py
Remove it from docs. Also mention module expects both or none of `auth_user`, `auth_password`.
=> use_auth is not a parameter for smpt module

examples/oidc_config_setup_azure_ad.yml, plugins/modules/oidc_config.py
oidc module has no `state` param.
Example in oidc.py is updated with copy-paste friendly values.
Example in examples/ is update to be runnable with `-e`. E.g. with `ansible-playbook -e oidc_client_id=my_id ...` you can directly setup a valid configuration.
=> Fix OIDC typo

plugins/modules/time_zone_info.py
The description in ``time_zone_info`` was not about the said module (copy-paste mistake), so it had to be changed.
=> Fix documentation for time_zone_info.

plugins/modules/smtp.py
Document smtp module is not idempotent if authentication is used
=> Document smtp module is not idempotent if authentication is used

.github/workflows/integ-test.yml, changelogs/fragments/cluster_config_role.yml, examples/cluster_config.yml, roles/cluster_config/README.md, roles/cluster_config/meta/argument_specs.yml, roles/cluster_config/tasks/main.yml, tests/integration/targets/role_cluster_config/tasks/apply_and_test.yml, tests/integration/targets/role_cluster_config/tasks/main.yml, tests/integration/targets/role_cluster_config/tasks/partial_update.yml, tests/integration/targets/role_cluster_config/tasks/revert_cluster_configuration.yml
The PR adds a role for initial cluster configuration. Role primary usage is to configure an empty cluster.
A dict to fully configure cluster looks like:
```
scale_computing_hypercore_cluster_config:
name: cluster-a
registration:
company_name: New company a
contact: John Smith a
phone: 056789000
email: john_smith_a@gmail.com
dns:
server_ips:
- 1.1.1.1
- 1.0.0.1
search_domains:
- subdomain_1.example.com
- subdomain_2.example.com
oidc:
client_id: 12345a
shared_secret: secret_stuff_a
config_url: https://login.microsoftonline.com/76d4c62a-a9ca-4dc2-9187-e2cc4d9abe7f/v2.0/.well-known/openid-configuration
scopes: openid+profile
time_server: 2.pool.ntp.org
time_zone: Europe/Ljubljana
smtp:
server: mail_a.example.com
port: 25
from_address: "ci-test-a@example.com"
email_alerts:
- user_a1@test.com …
```
=> cluster_config role

changelogs/fragments/support_tunnel_modules.yml, changelogs/fragments/version_update.yml
Added changelog fragment for version update modules.
Updated support tunnel fragment.
=> Add missing changelog fragment

plugins/modules/time_server_info.py
There was an old commented documentation part in ``time_server_info``, which is now irrelevant, so it was removed so as to not confuse others that may look into this code.
=> Remove irrelevant commented old documentation from time_server_info.

.github/workflows/integ-test.yml, examples/time_server.yml, examples/time_server_info.yml, examples/time_zone.yml, examples/time_zone_info.yml
Added workflows to run examples from ``examples/`` directory.
Examples are run in check mode.
=> Add examples run to workflow.

.github/workflows/integ-test.yml, examples/certificate_signing_example.yml, examples/dns_config.yml, examples/email_alert.yml, examples/list_vms_with_ide_disk.yml, examples/smtp.yml, examples/time_server.yml, examples/time_zone_info.yml, examples/virtual_disk.yml, tests/integration/prepare/prepare_examples.yml
Run only selected tasks from examples in check mode.
Before: 7 examples failed - https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4366501744/jobs/7636608279 
After:
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4367162558, 3 examples failed
- 1 more fix, in https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4367299898, 2 examples should fail.
=> Ci example and check mode

.github/workflows/ci-test.yml, .github/workflows/integ-test.yml, ci-infra/docker-image/.gitignore, ci-infra/docker-image/Dockerfile, ci-infra/docker-image/build.sh
We will use a custom docker image to run CI tests. Before we started with `python:3.10-slim-buster`, and need to run `apt install make git jq ...`, `pip install *.requirements`, and `pip install ansible` each time. All those tools will be part of our docker image.
This is example job with new docker image - https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4384232780/jobs/7675462776. It took about 20 sec.
The image contains latest ansible-2.13. I expect we will need at some point built more images (for ansbible 2.13, 2.14, etc). This is reason `ARG ANSIBLE_CORE_VERSION=2.13.0` parameter in Dockerfile - it allows to override ANSIBLE_CORE_VERSION outside of Dockerfile.
The docker image is stored under my personal quay.io account. Everyone can be pulled it, but login …
=> Ci docker image

roles/version_update_single_node/tasks/shutdown_vms.yml, roles/version_update_single_node/tasks/update_status_check.yml
There was a typo in ``roles/version_update_single_node/update_status_check.yml``, so that had to be fixed.
In ``roles/version_update_single_node/shutdown_vms.yml`` shutting down VMs was done by using "stop" power state (force shutdwon) right away. This was changed, so that we first try shutting down VMs usinng the "shutdown" power state (regular shutdown) and then, if that fails, we use "stop" power state to forcibly shut down the rest of the VMs.
=> Fix typo in update_status_check, fix force shutdown.

plugins/modules/vm.py, plugins/modules/vm_params.py
Extend VM shutdown options documentation. I do not want to duplicate what is already documented in Scale docs, but this one is just easy to miss. We ended using force shutdown during node upgrade - bad. So we need a bit more documentation.
=> Document VM shutdown options

roles/version_update_single_node/tasks/shutdown_vms.yml, roles/version_update_single_node/tasks/wait_vm_shutdown.yml
Noticed that we do start ACPI shutdown. But VM with Porteus-XFCE-v5.0-x86_64.iso was still shutting down when we already send force shutdown. PR tries to fix this.
=> Wait of VMs to finish ACPI shutdown

.github/workflows/integ-test.yml, tests/integration/integration_config.yml.template
Initially we had a configuration variable/secret for every possible line in `integration_config.yml`. Later we decided to have whole `integration_config.yml` except about 3 passwords as a single CI variable, and then we add only missing passwords to it.
The `smb_cleanup.sh` was not yet updated to get required configuration (SMB server, username etc) from `integration_config.yml`. This PR does this.
CI job to show that `smb_cleanup` integration "test" does pass - https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4465664492/jobs/7842970112
=> CI use SMB cleanup variables from integration_config.yml

changelogs/fragments/version_update_status_info_bugfix.yml, examples/version_update_status_info.yml, plugins/module_utils/hypercore_version.py, plugins/modules/version_update_status_info.py, tests/unit/plugins/module_utils/test_hypercore_version.py, tests/unit/plugins/modules/test_version_update_status_info.py
In case of “fresh cluster” no updates have ever been done so no update_status.json exists yet. Instead "404 Not found" is returned which caused module version_update_status_info (and consequently the version_update_single_node role) to fail.
With this PR the version_update_status_info module is fixed but the role version_update_single_node still needs to be revisited.
=> Handle case when update_status.json doesnt exist

.github/workflows/ci-test.yml, .github/workflows/integ-test.yml, plugins/modules/vm_snapshot_info.py
=> CI fix ANSIBLE_COLLECTIONS_PATH for docs

plugins/modules/api.py, plugins/modules/iso.py, tests/unit/plugins/modules/test_api.py
It is safer to always PUT binary data to HC3 with  Content-Length HTTP header.
PUT is used only in api, iso (and in future in virtual_disk module).
This does fix uploading virtual disk using raw api module example - `examples/virtual_disk.yml`.
It will also allow integration test for virtual_disk_info module to pass (the test VD is uploaded using api module).
=> Http put with content length

tests/integration/targets/virtual_disk_info/tasks/main.yml
Half-uploaded virtual disk with name "uploading-ci-test-virtual-disk-1.qcow2" needs to be removed before we can upload a new "ci-test-virtual-disk-1.qcow2".
=> CI Remove old half-uploaded virtual disk before upload

.github/workflows/ci-test.yml, .github/workflows/integ-test.yml, ci-infra/docker-image/Dockerfile, ci-infra/docker-image/build.sh, plugins/module_utils/client.py, plugins/modules/certificate.py, tests/integration/targets/certificate/files/pyproxy.py, tests/integration/targets/certificate/tasks/01_normal.yml, tests/integration/targets/certificate/tasks/02_ssl_eof_error.yml, tests/integration/targets/certificate/tasks/main.yml
@ddemlow had problem replacing certificate, and this happened only it server  was access via VPN. Likely VPN resulted in just correct timing to raise unexpected SSL error - in python code we got "EOF occurred in violation of protocol (_ssl.c:997)".
PR catches ScaleComputingError exception, and checks if message had this particular message inside.
I didn't try to refactor the ScaleComputingError to have a dedicated exception - I'm not able to reproduce the problem, so it is hard to test any code modification. For same reason, it is hard to add any integration test for this.
The extra `module.warn` were added, to help debugging if anything similar happens later. I hope warn message is kind enough ("... ignore and continue") - I do not want to make anyone nervous.
=> Ignore SSL protocol violation during certificate replacement

.github/actions/make-integ-config/action.yml, .github/workflows/integ-test.yml
Run integration tests against 9.1 and 9.2 API. 
Test will run on VSNS (virtual single node clusters). This means we will be able to easy revert changes, but we will also not be able to test upgrades (we do not test them with CI anyway). Those two VSNS nodes also do not have remote replication configured - that can be added if/when we need it in out testing.
Some things will required later "fine tunning". Like what to do with virtual_disk test on 9.1. We can just skip it, or we can check if expected error message ("your server version X does not support Y feature") is shown. I plan to work on this in separate PRs.
=> CI run integration tests against multiple HyperCore versions

.ansible-lint, .github/workflows/ci-test.yml, examples/api_get_cluster_info.yml, examples/certificate_signing_example.yml, examples/cluster_config.yml, examples/dns_config_info.yml, examples/email_alert_info.yml, examples/iso.yml, examples/iso_info.yml, examples/list_vms_with_ide_disk.yml, examples/oidc_config_setup_azure_ad.yml, examples/smtp.yml, examples/smtp_info.yml, examples/syslog_server.yml, examples/time_server_info.yml, examples/time_zone_info.yml, examples/version_update_single_node.yml, examples/version_update_status_info.yml, examples/virtual_disk.yml, examples/virtual_disk_info.yml, examples/vm_info.yml, examples/vm_replication_info.yml
CI test in https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4565210170/jobs/8056017663 failed. Problem was `ansible.builtin.assert` `fail_msg` vs. `fail_message`, in `examples/version_update_single_node.yml`.
ansible-lint is now run also on examples, in hope such mistakes will be catched. While ansible-list can complain `namex` is not valid param for `ansible.builtin.include_role`, it still didn't report `fail_message` as invalid param for assert. I still decided it is useful to lint examples, and fix linter errors.
=> Ansible lint for examples

changelogs/fragments/version_update_info_add_option.yml, examples/version_update_info.yml, plugins/modules/version_update_info.py, tests/integration/targets/version_update_info/tasks/main.yml, tests/unit/plugins/modules/test_version_update_info.py
To be able to choose next (the lowest number) or latest (the highest number) update from the list of available updates, next and latest are added to return value.
=> Add next and latest to return value

ci-infra/ntp-chrony/Readme.md, ci-infra/ntp-chrony/chrony.conf, tests/integration/integration_config.yml.j2, tests/integration/targets/email_alert/tasks/02_email_alert.yml, tests/integration/targets/inventory/runme.sh, tests/integration/targets/registration/tasks/main.yml, tests/integration/targets/remote_cluster_info/tasks/main.yml, tests/integration/targets/role_cluster_config/tasks/main.yml, tests/integration/targets/time_server/tasks/01_time_server_info.yml, tests/integration/targets/time_server/tasks/02_time_server.yml, tests/integration/targets/version_update_status_info/tasks/main.yml
Another 6 integration tests should get fixed by this PR.
Just trivial changes.
The biggest (I mean, most trivial) change is we now have 2 dedicated NTP servers just for testing.
=> Ci fix small problems with integration tests

examples/version_update_info.yml, examples/version_update_single_node.yml, roles/check_local_time/tasks/main.yml, roles/version_update_single_node/tasks/main.yml, tests/integration/targets/role_check_local_time/tasks/main.yml
The job https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4625947983/jobs/8182193452#step:9:55 failed.
The `ansible.builtin.set_fact: executable="{{ executable_python }}"` got executed (I think), and then `executable.stdout_lines` - there is no `stdout_lines` in `executable`.
Whole 3 tasks are just to hard to understand, and also to test.
The PR will switch to use `discovered_interpreter_python`. I think this will just work, even if playbook would be executed over SSH.
The version_update_single_node assumed `version_update_status_info` always returns `record`. But if cluster was never upgraded, then no record is returned. This is fixed now.
The CI job for this example will still fail - we cannot really upgrade any of our test clusters.
And I do not have a good idea …
=> Fix roles check_local_time, version_update_single_node

.github/workflows/static.yml
The PR adds github action to deploy documentation when:
- when new code is pushed to gh-pages branch.
- we manually run corresponding action. In this case source branch/tag can be selected.
Example manually run action - https://github.com/justinc1/HyperCoreAnsibleCollection/actions/runs/4667144279.
Rendered documentation is at https://justinc1.github.io/HyperCoreAnsibleCollection/
We will need to protect gh-pages branch (no force push).
After merge to main, I will cherry-pick this for release 1.2.0 too.
=> Use github pages action

docs/rst/extra/deprecation.rst, docs/rst/extra/quickstart.rst, docs/rst/index.rst, examples/iso.yml, examples/snapshot_schedule.yml, examples/vm.yml, examples/vm_nic.yml, plugins/modules/iso.py, plugins/modules/snapshot_schedule.py, plugins/modules/vm.py, plugins/modules/vm_nic.py
Running `ansible-playbook examples/vm.yml` shows 
```
TASK [Create VM demo-vm] ******************************************************************************
[DEPRECATION WARNING]: The 'record' return value will be changed from list (containing a single item) to dict. There will be no release where both old and 
new variant work at the same time. To ease migration, the only change between last 1.x or 2.x release and 3.0.0 release will be changing the 'record' 
return value. Affected modules are vm and snapshot_schedule. This feature will be removed from scale_computing.hypercore in version 3.0.0. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]
```
Examples for `vm` and `snapshot_schedule` modules were added.
Examples for `vm`, …
=> deprecation for vm and snapshot_schedule return value

plugins/modules/vm_boot_devices.py, plugins/modules/vm_disk.py, plugins/modules/vm_nic.py
Text from vm/vm_params module is reused.
=> Document vm_rebooted return field

tests/integration/targets/role_check_local_time/tasks/main.yml
Jobs
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4675127388/jobs/8279941573#step:8:52 and
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4675127388/jobs/8279941761#step:8:52 failed
Extra debug print added. It is not clear what were input values, and what went wrong.
Tested interval is also changed, this should make test more reliable.
Downside is test cannot work 2 hours in a day - there is extra assert just to fail early when this happens. It should not happen during scheduled CI jobs.
Removed the extra "" in asserts. We were checking string is not empty, but we need to let assert evaluate string.
=> CI try to fix check_local_time integ test

tests/integration/targets/version_update/tasks/main.yml
Two corner cases fixed.
1st if cluster was never upgrade before, the `version_update_status_info` module will return `record=None`. 
2nd, after one upgrade failed (upgrade was initiated, after a while is stopped with "Failed to open update tunnel") the `version_update_status_info` module does return  `record.update_status=None`.
=> Fix version update role

examples/version_update_single_node.yml, tests/integration/integration_config.yml.j2, tests/integration/targets/role_version_update_single_node/tasks/main.yml, tests/integration/targets/version_update_info/tasks/main.yml
Job
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4675127388/jobs/8279938549 failed.
New SW version 9.1.24.211326 was released.
=> CI expect latest new GA release 9.1.24

roles/check_local_time/tasks/main.yml
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4686722374/jobs/8305135195#step:9:48 Here ansible_python_interpreter was not defined.
See also https://github.com/ansible/ansible/issues/21311 and https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html I missed before that ansible_python_interpreter is not always defined.
We do not want to force user to tell us some valid python interpreter. Also, it would be possible that the only availble python is in venv or in /usr/local/bin (python docker images).
ansible_playbook_python looks like a suitable fallback. It is interpreter on the controller node. Our script will always run there - we never ssh to HyperCore controller.
=> Fix python interpreter for check_local_time.py script

tests/integration/targets/email_alert/tasks/02_email_alert.yml
A CI job taht failed
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4686722374/jobs/8305879487#step:8:188 If we really want to send email, then we would need our own SMTP server, or we would get some test email address where arbitrary spam would be accepted.
=> CI do not expect test will actually be able to send an email

tests/integration/targets/role_check_local_time/tasks/main.yml
Failed CI job
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4696220997/jobs/8326124886#step:8:49
The timezone from https://ipapi.co/timezone is correct one, it is based on public IP address/geolocation.
But out test ansible controller is not configured with timezone. UTC is just OK for servers.
We can convert unix epoch to local time with python and use pytz for that. pytz is used only for testing.
The timezone from ipapi.co is not needed anymore.
integ test after change:
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4697144688
=> CI do not assume test ansible controller has configured timezone

plugins/module_utils/client.py, plugins/module_utils/cluster.py, plugins/module_utils/errors.py, plugins/module_utils/rest_client.py, tests/unit/plugins/module_utils/test_cluster.py
Use ConnectionRefusedError in cluster shutdown instead of error description comparison
Closes #137
=> Cluster shutdown module exception handling update

plugins/module_utils/support_tunnel.py, tests/unit/plugins/conftest.py, tests/unit/plugins/module_utils/test_support_tunnel.py
Each support tunnel open/close will include a username in the log. Printscreen:
Fixes #205
=> Log username for support-tunnel open/close

examples/shutdown_restart_tagged_vms.yml, roles/version_update_single_node/defaults/main.yml, roles/version_update_single_node/meta/argument_specs.yml, roles/version_update_single_node/tasks/main.yml, roles/version_update_single_node/tasks/restart_vms.yml, roles/version_update_single_node/tasks/shutdown_vms.yml, roles/version_update_single_node/tasks/wait_vm_shutdown.yml, tests/integration/integration_config.yml.j2, tests/integration/targets/version_update__shutdown_restart_vms/tasks/01_shutdown_all.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/02_shutdown_none.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/03_shutdown_some.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/04_shutdown_tagged_a.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/05_shutdown_tagged_bc.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/helper_create_vms.yml, tests/integration/targets/version_update__shutdown_restart_vms/tasks/main.yml
We already had a role with taskfile `shutdown_vms` to shutdown all VMs. This is used to shutdown all VMs in a single node cluster before version upgrade, and to start them back after upgrade.
The PR extended `shutdown_vms` with option to shutdown only some VMs. VM tag is used to decide if VM needs to be shutdown. This will be used during multinode cluster version upgrade to shutdown VMs than should not be live-migrated to another node. See also #198.
Integration test in https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/4799944517
=> Shutdown tagged vms

roles/version_update_single_node/tasks/update_status_check.yml
We had a race condition. Sometimes a magic 60 sec delay was not enough to get update/update_status.json API endpoint work. The version_update_status_info now (it didn't initially) returns None in this case, so we can use that.
=> Fix update status check

roles/version_update_single_node/tasks/main.yml
The version_update_status_info uses undocumented API endpoint, it is hard to know what is returned. I believe we wanted to have `==COMPLETE`, not `==COMPLETED`.
I believe whole condition is there only to prevent starting second upgrade before the first one is finished -
`.update_status != "IN PROGRESS"` is sufficient.
A corner case would be if `.update_status == SOME_ERROR` or similar. In this case `!= "IN PROGRESS"` would still allow starting an upgrade. The `==COMPLETE` is again not needed - better to remove it, it just adds to confusion.
=> Cleanup unneeded condition

roles/version_update_single_node/tasks/main.yml, roles/version_update_single_node/tasks/shutdown_vms.yml, roles/version_update_single_node/tasks/wait_vm_shutdown.yml, tests/integration/targets/role_version_update_single_node/tasks/main.yml
Some VMs didn't want to receive a shutdown request, so ``version_update_single_node`` was updated so that the shutdown request is sent multiple times - in a loop.
=> Fix version_update_single_node to send shutdown request multiple times.

roles/version_update_single_node/README.md, roles/version_update_single_node/meta/argument_specs.yml
The role  version_update_single_node was missing a Readme.md file. PR does add it, and also shortly describes steps performed by the role.
=> Add README.md to version_update_single_node role

tests/config.yml
Ignore unsupported Python sanity tests (compile-2.7, compile-3.5, compile-3.6) by using the tests/config.yml file. 
By specifying `python_requires: '>=3.8'`, the `ansible-test sanity` tests will skip python-specific tests for any lower version than 3.8. 
This will create a clean import log in Automation Hub for the next certified release (assuming no other errors).
=> Create config.yml - ignore Python sanity tests for unsupported Python

roles/README.md
import to automatin hub for v1.2.0 reported warning Could not get role description, no role metadata found
Per https://github.com/kubernetes-sigs/kubespray/issues/9048#issuecomment-1221334912 adding roles/README.md should help.
Please do not merge the PR. I prefer rebase, I might need to cherry-pick this PR/commit for v1.2.x.
=> Add README.md to roles directory

docs/rst/extra/quickstart.rst, examples/cloud-init-user-data-example.yml, plugins/modules/vm.py, plugins/modules/vm_clone.py, plugins/modules/vm_import.py
A number of examples were including user-data content into meta-data section, and user-data section containing a bogus meta-data content.
Change this, examples should be close to valid and runnuble example.
Also add extra note to user-data example file that the file must begin with magic comment. This is always very easy to miss.
=> Fix cloud-init meta-data/user-data content being mixed

changelogs/fragments/hypercore_inventory_bugfix.yml, plugins/inventory/hypercore.py, tests/integration/targets/inventory/cleanup.yml, tests/integration/targets/inventory/prepare.yml, tests/integration/targets/inventory/run_ansible_both_false_tests.yml, tests/integration/targets/inventory/run_ansible_both_true_tests.yml, tests/integration/targets/inventory/run_ansible_disable_tests.yml, tests/integration/targets/inventory/run_ansible_enable_tests.yml, tests/integration/targets/inventory/runme.sh
When reading timeout from env variable SC_TIMEOUT (which is string) it needs to be changed to int to avoid inventory parse error (specifically error in "/usr/lib/python3.10/socket.py", line 830, in create_connection sock.settimeout(timeout)). 
Also try-except was removed since KeyError is not raised in case if env variable doesn't exist.
=> Inventory - sc_timeout changed to int

plugins/module_utils/vm_snapshot.py, plugins/modules/vm_snapshot_attach_disk.py, tests/integration/targets/vm_snapshot/tasks/01_vm_snapshot_info.yml, tests/integration/targets/vm_snapshot/tasks/03_vm_snapshot_attach_disk.yml, tests/integration/targets/vm_snapshot/tasks/helper_api_vm_snapshot_create.yml, tests/integration/targets/vm_snapshot/tasks/helper_check_vm_state.yml, tests/integration/targets/vm_snapshot/tasks/main.yml, tests/unit/plugins/modules/test_vm_snapshot_attach_disk.py
This PR makes sure that the VM we are trying to attach a snapshot disk to shuts down before attaching; tasks fail if we are trying to attach to a running VM.
**How it works (steps)**:
1. if the destination VM is running, shut it down (first normally, and if that fails, then forcibly) - this step is skipped if the VM is already shut down.
2. attach the desired snapshot disk
3. restart the destination VM.
=> Add shutdown destination VM functionallity before attaching a disk from a source snapshot.

plugins/modules/vm_snapshot_attach_disk.py, tests/integration/targets/vm_snapshot/tasks/03_vm_snapshot_attach_disk.yml, tests/unit/plugins/modules/test_vm_snapshot_attach_disk.py
A small change to ``vm_snapshot_attach_disk`` was made as requested in #233.
- add ``vm_rebooted`` status to return --> info if reboot of the destination VM was performed.
=> Update return of vm_snapshot_attach_disk module.

.github/workflows/ci-test.yml, .github/workflows/integ-test.yml
Examples testing job was always run before the integration testing job which made waiting for integration tests to finish even longer then it was supposed to. This pull request fixes this problem by updating the ``examples-run`` job to make it run after the ``integ`` job finishes regardless of the status.
Jobs ``examples-run`` and ``integ`` can be found in ``.github/workflows/integ-test.yml``.
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/5003937671
Timestamp of the last integration test to succeed ([here](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/5003937671/jobs/8965837295)):
```
Run echo "Integ time -> $(date +%T)" && exit 0
Integ time -> 13:44:08
```
Timestamp of the first example test to run …
=> Make examples testing job run after integration tests

.github/actions/make-integ-config/action.yml, .github/workflows/integ-test.yml, plugins/doc_fragments/cluster_instance.py, plugins/inventory/hypercore.py, plugins/module_utils/arguments.py, plugins/module_utils/client.py, plugins/module_utils/typed_classes.py, tests/integration/integration_config.yml.j2, tests/integration/targets/inventory/runme.sh, tests/integration/targets/utils_login/tasks/main.yml, tests/unit/plugins/module_utils/test_client.py, tests/unit/plugins/module_utils/test_rest_client_CachedRestClient.py
PR allows collection to login to HyperCore cluster using a username form external OIDC provider. New environ varibale `SC_AUTH_METHOD` (possible value None/unset, `local` or `oidc`) is added as we need to know where is user defined.
Previously we used HTTP basic login for each request. PR first refactored code to get sessionID from HC3 and reuse it for subsequent requests. 
Since OIDC is configured on .50 test cluster only, the CI job `utils_login` will be run only there.
The inventory plugin will run on .200 and .201 VSNS (just as before). But since we do not test OIDC on VSNS, OIDC is not configured there, so now we test inventory plugin on .50 also, and there (and only there) inventory plugin with OIDC user is tested.
=> OIDC login

examples/vm_snapshot_attach_disk.yml
Per slack discussion we can have max 26 devices per bus. PR changed invalid disk slot in our example.
=> Avoid invalid disk_slot in example

examples/version_update_single_node.yml, tests/integration/integration_config.yml.j2
In tests we have hardcoded expected HyperCore version. The 9.2.17 is GA (general availability), so this is what our test cluster should report as next available version.
I hate we need to manually bump this string every few weeks. Maybe we should have more complex integration test that could check not only "next_version == 9.2.17.211525", but also "next_version >= 9.2.17.211525".
=> Bump expected latest released HyperCore version

DEVELOPMENT.md
An additional step for preparing the environment is needed, so it was added to the ``DEVELOPMENT.md`` file.
The added/updated step was the command:
```
ansible-galaxy collection install community.general community.crypto
```
=> Update DEVELOPMENT.md with additional preparation step

plugins/module_utils/task_tag.py, tests/unit/plugins/module_utils/test_task_tag.py
Show details of failed TaskTag if TaskTag fails on HyperCore side.
Sample output before PR:
```
TASK [Create VM demo-vm for examples/vm_replication_info.yml] ******************************************************************************
fatal: [localhost]: FAILED! => changed=false 
msg: There was a problem during this task execution.
```
Sample output after PR:
```
TASK [Create VM demo-vm for examples/vm_replication_info.yml] ******************************************************************************
fatal: [localhost]: FAILED! => changed=false 
msg: 'There was a problem during this task execution. Task details: {"taskTag": "204", "progressPercent": 0, "state": "ERROR", "formattedDescription": "Delete block device %@ for Virtual Machine %@", "descriptionParameters": ["9dc1c6eb", …
```
=> Show details about failed task

DEVELOPMENT.md, plugins/module_utils/client.py
I had problem figuring out why Ansible task fails with "500 Internal server error". The PR helps by logging HTTP requests/responses into a log file, and we can do post-mortem analysis.
My sample problem become obvious. Two subsequent requests are shown:
```
tail -f /tmp/q
41.6s _request: 
request_in={'data': None, 'headers': {'Accept': 'application/json', 'Cookie': 'sessionID=cad85149-2418-4d17-b5b3-e190d1cf647e'}, 'method': 'DELETE', 'path': 'https://172.31.6.11/rest/v1/VirDomainBlockDevice/a795ef22-4f5b-43e3-94cb-d1fb1ea53462', 'timeout': 60.0},
request_out={'data': b'{"taskTag":"449","createdUUID":""}', 'headers': {'access-control-allow-origin': '*', 'connection': 'close', 'content-length': '34', 'content-type': 'application/json; charset=utf-8', 'date': 'Mon, 03 Jul 2023 06:34:43 …
```
=> Store HTTP requests/responses into a log file

plugins/module_utils/disk.py, plugins/module_utils/errors.py, plugins/module_utils/task_tag.py, plugins/module_utils/vm.py, plugins/modules/vm.py, plugins/modules/vm_disk.py, tests/integration/targets/vm__remove_disk/tasks/01_remove_disk_stopped.yml, tests/integration/targets/vm__remove_disk/tasks/02_remove_disk_running.yml, tests/integration/targets/vm__remove_disk/tasks/03_remove_disk_running_with_reboot.yml, tests/integration/targets/vm__remove_disk/tasks/main.yml, tests/integration/targets/vm_disk__remove_disk/tasks/01_remove_disk_stopped.yml, tests/integration/targets/vm_disk__remove_disk/tasks/02_remove_disk_running.yml, tests/integration/targets/vm_disk__remove_disk/tasks/03_remove_disk_running_with_reboot.yml, tests/integration/targets/vm_disk__remove_disk/tasks/main.yml
Sometimes we can remove disk from a running VM, and sometimes we need to shutdown VM before disk can be removed. It depends on HyperCore thinking VM might be using the disk.
The PR:
- first tries to remove disk from a running VM (the behaviour before this PR)
- if this fails, it shutdowns VM, tries delete a second time and start VM back
Integration tests for all this is included, for `vm` and `vm_disk` modules. It covers 3 cases:
- VM being off
- VM running and cannot be shutdown (it does not respond to nice shutdown, and force shutdown is not allowed)
- VM running and can be shutdown (force shutdown is allowed)
A small bug in vm_disk module was also fixed. The module didn't start back VM if it was shutdown during execution.
=> Fix vm disk remove

tests/integration/targets/vm_clone/tasks/01_cleanup.yml, tests/integration/targets/vm_clone/tasks/14_clone_from_snapshot.yml
The vm_clone works correctly. The test however assumed vm_snapshot_info output is sorted. But it is not. PR now sorts output from vm_snapshot_info before using one of two snapshots with `label=="test2"`.
Test is `14_clone_from_snapshot.yml` a bit modified, each of 3 snapshots has a different CPU and disk count. Then it is easier to check that correct snapshot was used to create a new VM.
=> Fix vm clone test

roles/version_update_single_node/tasks/shutdown_vms.yml
Default value of version_update_single_node_shutdown_wait_time is str, not int. This is because default value is computed in roles/version_update_single_node/defaults/main.yml.
Fixes #257
=> Fix bug - default type of version_update_single_node_shutdown_wait_time

roles/version_update_single_node/tasks/update_status_check.yml
I removed the magic delay, and then role sometimes does not work. The PR basically just reverts the old commit.
Fixes #258
=> Missing wait in version_update_role

.github/workflows/integ-test.yml, examples/version_update_single_node.yml, plugins/module_utils/client.py, tests/integration/cleanup/ci_replica_cleanup.yml, tests/integration/cleanup/smb_cleanup.sh, tests/integration/integration_config.yml.j2
Only small fixes. The debug HTTP request logging can be enabled with `SC_DEBUG_LOG_TRAFFIC=1` environ variable.  The code crashed if request timed out, as we wanted to log HTTP response, but variable was not set.
The CI test need to expect 9.2.17.211525 as available update (HyperCore version upgrade).
The cleanup on SMB server is modified to run even if tests fail. The cleanup will remove all files not from current month (before: not from current day). This cloud interfere with tests on first/last day of month, but in practice we should not have a problem as the cleanup will be scheduled before tests.
Similar for DR target cluster, we will remove all VMs older that 2 days. Should not interfere with tests at all.
Here we remove all old replicated VMs with tag "Xlab" (before tag Xlab and CI …
=> Small fixes

plugins/modules/snapshot_schedule.py, plugins/modules/virtual_disk.py, tests/integration/prepare/prepare_iso.yml, tests/integration/targets/i_vm_params/tasks/main.yml, tests/integration/targets/iso/tasks/main.yml, tests/integration/targets/vm__remove_disk/tasks/main.yml, tests/integration/targets/vm_boot_devices/tasks/main.yml, tests/integration/targets/vm_disk/tasks/main.yml, tests/unit/plugins/modules/test_snapshot_schedule.py
We were missing wait on tasktag for SnapshotSchedule create, and wait on object begin delete for SnapshotSchedule and VirtualDisk.
Other changes are just small CI speedup, and fix how CI test check if HyperCore version >= 9.2.
=> Ci for 9.3

plugins/module_utils/vm.py, plugins/modules/vm.py, tests/integration/targets/vm__min_params/tasks/main.yml, tests/unit/plugins/conftest.py, tests/unit/plugins/module_utils/test_vm.py, tests/unit/plugins/modules/test_vm.py
On HyperCore v9.3 we can POST `machineTypeKeyword` instead of `machineType`. In addition, GET responses have new possible values for `machineType`.
Fixes #262
=> Fix for machine_type on HyperCore 9.3

plugins/module_utils/email_alert.py, plugins/modules/email_alert.py, tests/integration/targets/email_alert/tasks/01_email_alert_info.yml, tests/integration/targets/email_alert/tasks/02_email_alert.yml, tests/integration/targets/email_alert/tasks/03_email_alert_duplicated.yml, tests/integration/targets/email_alert/tasks/helper_api_email_alert_create_one.yml, tests/integration/targets/email_alert/tasks/helper_api_email_alert_delete_all.yml, tests/integration/targets/email_alert/tasks/helper_api_email_alert_reset.yml, tests/integration/targets/email_alert/tasks/main.yml, tests/unit/plugins/modules/test_email_alert.py
When removing email alerts we need to allow duplicated emails.
Fixes #264
=> Remove duplicated email alerts

tests/integration/targets/vm_clone/tasks/10_clone_stopped.yml, tests/integration/targets/vm_clone/tasks/11_clone_stopped_cloudinit.yml, tests/integration/targets/vm_clone/tasks/12_clone_running.yml, tests/integration/targets/vm_clone/tasks/13_clone_stopped_preserve_mac.yml, tests/integration/targets/vm_clone/tasks/main.yml
CI test was comparing wrong variables in a few places. PR fixes that.
PR also make sure we can run a single sub-test after
test/source VMs were prepared.
Fixes #273
TY @shoriminimoe for noticing this.
=> CI vm_clone fix wrong variable being used

tests/integration/integration_config.yml.j2
For some reason, VSNS201 does not offer update to 9.2.24.212633. There is no available update also in GUI.
The VSNS200 shows update 9.2.24.212633 as available.
=> CI fix expected version string

plugins/module_utils/vm.py, plugins/modules/vm.py, plugins/modules/vm_params.py, tests/integration/targets/i_vm_params/tasks/02_machine_type.yml, tests/unit/plugins/module_utils/test_vm.py, tests/unit/plugins/modules/test_vm.py
The test for vm_params__power_state was added recently (in #287), and it was failing.
See https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/8059420864/job/22068199119#step:8:138.
ACPI shutdown was just not sent to the VM.
The PR fixes this.
Integ test in https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/8284495601 and https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/8382148003
=> vm_params need to start/shutdown/reboot etc VM if requested

galaxy.yml
Having `tests/config.yml` in built `.tar.gz` should help `ansible-test sanity` to not test with old python version (2.7 etc).
=> Include tests/config.yml into tar.gz

.gitignore, DEVELOPMENT.md, ansible.cfg, changelogs/fragments/20240508-url2template.yml, examples/url2template/hypercore.yml, examples/url2template/meta-data.ubuntu-22.04.yml.j2, examples/url2template/template2vm.yml, examples/url2template/url2template.yml, examples/url2template/user-data.ubuntu-22.04.yml.j2, roles/template2vm/README.md, roles/template2vm/meta/argument_specs.yml, roles/template2vm/meta/main.yml, roles/template2vm/tasks/main.yml, roles/template2vm/tasks/wait_vm_boot_tasks.yml, roles/url2template/README.md, roles/url2template/meta/argument_specs.yml, roles/url2template/meta/main.yml, roles/url2template/tasks/main.yml
2 new roles are added.
url2template creates template VM from disk image URL.
Example URL is https://cloud-images.ubuntu.com/releases/22.04/release-20240416/ubuntu-22.04-server-cloudimg-amd64.img. 
Next template2url can be used to create new VMs from template VMs. Here we typically need to configure VM with cloud-init.
Cloud-init configuration data depends on the used image. A working example for above Ubuntu image is included.
=> url2template and template2vm roles

.github/job_retry_needed.py, .github/workflows/integ-test.yml, .github/workflows/z_ansible-test.yml, tests/integration/targets/vm_disk__remove_disk/tasks/01_remove_disk_stopped.yml, tests/integration/targets/vm_disk__remove_disk/tasks/02_remove_disk_running.yml, tests/integration/targets/vm_disk__remove_disk/tasks/03_remove_disk_running_with_reboot.yml
Running more than one CI test per HyperCore cluster is a bit problematic. PR refactor `integ-test` job to same pattern as we have for `integ-seq-test` - include the helper workflow `z_ansible-test.yml`. This allows running tests on all 4 clusters in parallel, and at most 1 test pre cluster.
Some tests require physical cluster. Those are run in newly added `integ-physical` job, on https://10.5.11.50.
We test examples with simple `ansible-playbook ... example_name.yml`. This does not work for some examples, so do not test those to avoid false failures.
=> Ci refactor

.github/workflows/ci-test.yml, .github/workflows/release.yml
Automates the steps to publish to the Ansible Automation Platform. This
requires the `AUTOMATION_PLATFORM_API_KEY` to be set in the repo
secrets.
=> ci(release): publish to Ansible Automation Platform

.github/workflows/files/ansible-test-units-matrix.yml
See
https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/9869001773/job/27251970472#step:4:707
The ansible-community/ansible-test-gh-action wants to use quay.io/ansible/default-test-container:1.10.1 image, and this image no longer works with a recent docker.
=> CI stop running unit tests with ansible 2.9

DEVELOPMENT.md
The github runner was configured back to IP it had before reboot (10.5.11.5). `DEVELOPMENT.md` is extended to mention NTP, SMB and OIDC setup we use in CI testing.
=> ci: document NTP server, SMB server and OIDC

tests/integration/targets/git_issue_41/tasks/issue_41_cloud_init_disks.yml
The git_issue_41 integration test failed in #328 with
```
fatal: [testhost]: FAILED! => {"msg": "The conditional check '\"{{ vm_created.record.0.disks.2.iso_name }}\" == \"cloud-init-{{ (vm_created.record.0.uuid | split(\"-\")) [0] }}.iso\"' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."}
```
PR fixes the testing code. I checked on my PC that test failed with ansible-core 2.16 before, and passed after.
=> ci: fix unsafe conditional

tests/integration/targets/inventory/tests/test_ansible_both_false.yml, tests/integration/targets/inventory/tests/test_ansible_both_true.yml, tests/integration/targets/inventory/tests/test_ansible_disable.yml, tests/integration/targets/inventory/tests/test_ansible_enable.yml
Warnings that are fixed were like
Warning: : conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{ 'localhost' in hostvars }}
=> ci: Remove jinja2 from assert, to avoid warnings

plugins/doc_fragments/cloud_init.py
Fixes #340
There was some confusion about why cloud-init ISO was not added to existing VM. Documentation should prevent confusion.
=> Document cloud-init is applied only to newly created VM

tests/integration/targets/virtual_disk/tasks/01_supported.yml
VirtualDisk upload test was failing. Even uploading emtpy disk image via web UI had problems (v9.4.21.216168). This change seems to help.
=> CI avoid testing virtual disk with empty disk image

tests/integration/targets/virtual_disk/tasks/02_not_supported.yml, tests/integration/targets/virtual_disk_attach/tasks/01_supported.yml
Continue #348. Some test disks were missed, were still empty.
Test: https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/12832531659/attempts/1
=> CI avoid testing virtual disk with empty disk image - continued

DEVELOPMENT.md, ci-infra/helpers/ci_hosts_recreate.yml, ci-infra/helpers/ci_hosts_recreate_one.yml
Add a helper script to recreate CI test clusters from template VMs.
@shoriminimoe I aleady used this. I assigned PR to you just to let you know playbook for this exists.
=> CI playbook to recreate CI test clusters

tests/integration/targets/vm_disk/tasks/main.yml
Using `vm_info` means we test what `vm_disk` actually changed on HyperCore cluster, not only what `vm_disk` return value (e.g. what `vm_disk` thinks it applied).
=> Extend vm_disk module tests - assert on vm_info output

examples/iso_eject.yml, plugins/module_utils/vm.py, plugins/modules/vm_disk.py, tests/integration/targets/vm__iso_eject/tasks/main.yml, tests/integration/targets/vm_disk__iso_eject/tasks/main.yml
Modules `vm` and `vm_disk` were not able to eject ISO image from CD-ROM device. Reported in #345. PR fixes this. It also adds integration tests for both modules, and an example playbook.
=> Fix ISO eject
